version: '2.4'
services:
  python:
    image: python:3.9.0-alpine3.12
    command: sh -c 'pip install -r requirements.txt && python -m unittest test.test-examples'
    working_dir: /app
    volumes:
      - .:/app
